export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const MARK_COMMENT_AS_FAV = 'MARK_COMMENT_AS_FAV';
export const CREATE_NEW_COMMENT = 'CREATE_NEW_COMMENT';
export const REMOVE_COMMENT_FROM_FAV = 'REMOVE_COMMENT_FROM_FAV';
